#!/bin/bash

source /usr/local/bin/tvcc/lib/functions

set_logon_script_televinken

gsettings set com.canonical.Unity.Launcher favorites "[
'application://nautilus-home.desktop',
'application://google-chrome.desktop',
'application://gnome-calculator.desktop',
'application://xpad.desktop',
'application://slack.desktop',
'unity://running-apps',
'application://wps-office-et.desktop',
'application://wps-office-wps.desktop',
'application:///usr/local/bin/tvcc/share/televinken/shortcuts/televinken-assistance.desktop',
'application:///usr/local/bin/tvcc/share/televinken/shortcuts/televinken-control-center.desktop',
'application:///usr/local/bin/tvcc/share/televinken/shortcuts/televinken-logout.desktop',
'application:///usr/local/bin/tvcc/share/televinken/shortcuts/televinken-reboot.desktop',
'unity://expo-icon',
'unity://devices']"

zenity --info --text "Your software has been updated to the latest version!" --timeout 5
