#!/bin/bash

function login_3foretag {

PERSON=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`


# Force Zenity Status message box to always be on top.
sleep 1 && wmctrl -r "Starting up" -b add,above &

(
# =================================================================
set_background_foretag
slacktee_logon_foretag
set_launcher_foretag
set_menues_foretag
backup_bria
backup_vm_conf
wmctrl -r "Starting up system" -b add,above &
echo "# Setting Preferences" ; sleep 4

# =================================================================
start_firefox_foretag
wmctrl -r "Starting up system" -b add,above &
echo "40"
echo "# Starting Web Browser" ; sleep 2

# =================================================================
startvm_foretag
wmctrl -r "Starting up" -b add,above &
echo "60"
echo "# Starting Virtual Machine" ; sleep 3

# =================================================================
#start_remote_foretag
timeout_foretag &
wmctrl -r "Starting up" -b add,above &
echo "70"
echo "# Starting RDS" ; sleep 2

# =================================================================
wmctrl -r "Starting up" -b add,above &
echo "# System Ready" ; sleep 2
echo "100"
#TEST COMMAND
remmina -i &

) |
zenity --progress \
  --title="Starting up" \
  --text="First Task." \
  --percentage=0 \
  --pulsate \
  --auto-close \
  --auto-kill

(( $? != 0 )) && zenity --error --text="Error: Could not complete task."

zenity --info --text "Welcome, $PERSON. System ready for use. V2.2" --timeout 5

exit 0


}

function login_3kundservice {

PERSON=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`


# Force Zenity Status message box to always be on top.
sleep 1 && wmctrl -r "Starting up system" -b add,above &

(
# =================================================================
slacktee_logon_kundservice
set_background_kundservice
set_launcher_kundservice
set_menues_kundservice
backup_bria
wmctrl -r "Starting up system" -b add,above &
echo "# Setting Preferences" ; sleep 4

# =================================================================
#start_remote_kundservice
timeout_kundservice &
wmctrl -r "Starting up" -b add,above &
echo "70"
echo "# Starting RDS" ; sleep 2

# =================================================================
remmina -i &
chown -R $USER:503 ~/.remmina/
chmod -R 700 ~/.remmina/
wmctrl -r "Starting up" -b add,above &
echo "# System Ready" ; sleep 2
echo "100"


) |
zenity --progress \
  --title="Starting up" \
  --text="First Task." \
  --percentage=0 \
  --pulsate \
  --auto-close \
  --auto-kill

(( $? != 0 )) && zenity --error --text="Error: Could not complete task."

zenity --info --text "Welcome, $PERSON. System ready for use. V2.2" --timeout 2 --no-wrap

exit 0


}

function login_3savedesk {

PERSON=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`


# Force Zenity Status message box to always be on top.
sleep 1 && wmctrl -r "Starting up system" -b add,above &

(
# =================================================================
slacktee_logon_3savedesk
set_background_3savedesk
set_launcher_3savedesk
set_menues_3savedesk
backup_bria
wmctrl -r "Starting up system" -b add,above &
echo "# Setting Preferences" ; sleep 4

# =================================================================
#start_remote_kundservice
timeout_3savedesk &
wmctrl -r "Starting up" -b add,above &
echo "70"
echo "# Starting RDS" ; sleep 2

# =================================================================
remmina -i &
chown -R $USER:503 ~/.remmina/
chmod -R 700 ~/.remmina/
wmctrl -r "Starting up" -b add,above &
echo "# System Ready" ; sleep 2
echo "100"


) |
zenity --progress \
  --title="Starting up" \
  --text="First Task." \
  --percentage=0 \
  --pulsate \
  --auto-close \
  --auto-kill

(( $? != 0 )) && zenity --error --text="Error: Could not complete task."

zenity --info --text "Welcome, $PERSON. System ready for use. V2.2" --timeout 2 --no-wrap



}


function login_3telesales {

PERSON=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`


# Force Zenity Status message box to always be on top.
sleep 1 && wmctrl -r "Starting up system" -b add,above &

(
# =================================================================
set_background_telesales
slacktee_logon_telesales
set_launcher_telesales
set_menues_telesales
backup_bria
wmctrl -r "Starting up system" -b add,above &
echo "# Setting Preferences" ; sleep 4

# =================================================================
start_pidgin
start_slack
wmctrl -r "Starting up" -b add,above &
echo "30"
echo "# Starting IM Client" ; sleep 2

# =================================================================
wmctrl -r "Starting up" -b add,above &
echo "40"
echo "# Starting Web Browser" ; sleep 2

# =================================================================
startvm_telesales
timeout_telesales &
wmctrl -r "Starting up" -b add,above &
echo "60"
echo "# Starting Virtual Machine" ; sleep 3

# =================================================================
start_remote_telesales
wmctrl -r "Starting up" -b add,above &
echo "70"
echo "# Starting RDS" ; sleep 2

# =================================================================
wmctrl -r "Starting up" -b add,above &
echo "# System Ready" ; sleep 2
echo "100"


) |
zenity --progress \
  --title="Starting up" \
  --text="First Task." \
  --percentage=0 \
  --pulsate \
  --auto-close \
  --auto-kill

(( $? != 0 )) && zenity --error --text="Error: Could not complete task."

zenity --info --text "Welcome, $PERSON. System ready for use. V2.2" --timeout 5

exit 0


}

function login_televinken {

PERSON=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`


# Force Zenity Status message box to always be on top.
sleep 1 && wmctrl -r "Starting up system" -b add,above &

(
# =================================================================
set_background_televinken
slacktee_logon_televinken
set_launcher_televinken
set_menues_televinken
backup_bria
wmctrl -r "Starting up system" -b add,above &
echo "# Setting Preferences" ; sleep 4

# =================================================================
#start_pidgin
start_slack
wmctrl -r "Starting up" -b add,above &
echo "30"
echo "# Starting up" ; sleep 2

# =================================================================
start_firefox_televinken
wmctrl -r "Starting up" -b add,above &
echo "40"
echo "# Starting Web Browser" ; sleep 2

# =================================================================
startvm_televinken
timeout_televinken &
wmctrl -r "Starting up" -b add,above &
echo "60"
echo "# Starting Virtual Machine" ; sleep 3


# =================================================================
wmctrl -r "Starting up" -b add,above &
echo "# System Ready" ; sleep 2
echo "100"


) |
zenity --progress \
  --title="Starting up" \
  --text="First Task." \
  --percentage=0 \
  --pulsate \
  --auto-close \
  --auto-kill

(( $? != 0 )) && zenity --error --text="Error: Could not complete task."

zenity --info --title "System Authority" --text "Welcome, $PERSON. System ready for use. V2.2" --timeout 5

exit 0


}

